REATE OR REPLACE TRIGGER "TRIG_SS_SURVEY"
BEFORE INSERT ON SS_SURVEY
FOR EACH ROW
BEGIN
	SELECT SS_SURVEY_ID.SEQ.NEXTVAL
	INTO :NEW.SURVEY_ID
	FROM DUAL 
END;
/


ALTER TRIGGER "TRIG_SS_SURVEY" ENABLE;