CREATE OR REPLACE TRIGGER "TRIG_SS_QUESTIONS"
BEFORE INSERT ON SS_QUESTIONS
FOR EACH ROW
BEGIN
	SELECT SS_QUESTION_ID.SEQ.NEXTVAL
	INTO :NEW.QUESTION_ID
	FROM DUAL 
END;
/


ALTER TRIGGER "TRIG_SS_QUESTIONS" ENABLE;