CREATE TABLE "SS_OPTIONS"
(
'OPTION_ID' NUMBER  
'SURVEY_ID' NUMBER,
 'QUESTION_NUMBER' NUMBER,
 'OPTION_VALUE' NUMBER,
CONSTRAINT "OPTION_ID_PK" PRIMARY KEY ("OPTION_ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STOARGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
TABLESPACE "DWH_DATA" ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
.NOCOMPRESS LOGGING
STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
TABLESPACE "DWH_DATA"

CREATE OR REPLACE TRIGGER "TRIG_SS_OPTIONS"
BEFORE INSERT ON SS_OPTIONS
FOR EACH ROW
BEGIN
	SELECT SS_OPTION_ID.SEQ.NEXTVAL
	INTO :NEW.OPTION_ID
	FROM DUAL 
END;
/


ALTER TRIGGER "TRIG_SS_OPTIONS" ENABLE;